### ISSUE TITLE
omni.py method _get_advertised_rspecs() causes harsh error

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#114]
Call to `listresources` with no aggregates defined (forcing an implicit call to `listaggregates`) with PLC credentials results in the following error:
```
$ ~/gcf/src/omni.py -c omni_config_plc_pi -f plc  listresources -t GENI 3 -V 2 -o
INFO:omni:Loading config file omni_config_plc_pi
INFO:omni:Using control framework plc
INFO:omni.sfa:SFA Registry: http://www.planet-lab.org:12345
INFO:omni.sfa:SFA Slice Manager: http://www.planet-lab.org:12347
INFO:omni:Saving output to a file.
Traceback (most recent call last):
  File "/home/sedwards/gcf/src/omni.py", line 2532, in <module>
    sys.exit(main())
  File "/home/sedwards/gcf/src/omni.py", line 2526, in main
    API_call(framework, config, args, opts, verbose=opts.verbose)
  File "/home/sedwards/gcf/src/omni.py", line 2260, in API_call
    result = handler._handle(args)
  File "/home/sedwards/gcf/src/omni.py", line 149, in _handle
    return getattr(self,call)(args[1:])
  File "/home/sedwards/gcf/src/omni.py", line 574, in listresources
    (rspecs, message) = self._listresources( args )
  File "/home/sedwards/gcf/src/omni.py", line 337, in _listresources
    (ad_rspec_version, message) = self._get_advertised_rspecs(client)
  File "/home/sedwards/gcf/src/omni.py", line 234, in _get_advertised_rspecs
    if thisVersion['code']['geni_code'] == 0:
KeyError: 'code'

```

Turns out that `_get_advertised_rspecs` has the following logic:
```
        if self.opts.api_version == 2:
               if thisVersion['code']['geni_code'] == 0:
<snip>
```

This implicitly assumes that each of the AMs you are talking to returned a AM API v2 GetVersion (which contains `'code'`) because you asked (hence the self.opts.api_version == 2).

This fails for AMs like `http://www.emulab.net:443/protogeni/xmlrpc/am` which supports AM API v1.

Make code more robust.

 _Imported from trac ticket [#114](http://trac.gpolab.bbn.com/gcf/ticket/114),  created by sedwards on 02-03-2012 at 21:36, last modified: 02-03-2012 at 21:43_

**Comment by seledwards** [comment]
Replaced the following:

```
        if self.opts.api_version == 2:
               if thisVersion['code']['geni_code'] == 0:
<snip>
```

with:

```
        if self.opts.api_version == 2:
            if not thisVersion.has_key('code'):
                # you ask for v2, but you got v1 so continue processing as v1
                pass
            elif thisVersion['code']['geni_code'] == 0:
<snip>
```
This means that `http://www.emulab.net:443/protogeni/xmlrpc/am` will generate an RSpec.

Alternatively could have done:
```
        if self.opts.api_version == 2:
            if not thisVersion.has_key('code'):
                # you ask for v2, but you got v1 so break now
                return (None, "AM %s does not have '%s' argument" % (client.url, ad_key))                
            elif thisVersion['code']['geni_code'] == 0:
<snip>
```
This would mean that `http://www.emulab.net:443/protogeni/xmlrpc/am` would not generate any RSpec.

Closing.  

_Trac comment by sedwards (github user: seledwards) on 02-03-2012 at 21:43_
