### ISSUE TITLE
omni: handle AM down in ListResources

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#131]
When the AM is down when ListResources calls GetVersion, you can get an ugly stack trace. Handle it more gracefully.
EG:
```

ERROR:omni.protogeni:Call for GetVersion at https://boss.utah.geniracks.net/protogeni/xmlrpc/am/2.0 failed.: Unknown socket error: [Errno -2] Name or service not known
ERROR:omni.protogeni:    ..... Run with --debug for more information
Traceback (most recent call last):
  File "./src/omni.py", line 2543, in <module>
    sys.exit(main())
  File "./src/omni.py", line 2537, in main
    API_call(framework, config, args, opts, verbose=opts.verbose)
  File "./src/omni.py", line 2261, in API_call
    result = handler._handle(args)
  File "./src/omni.py", line 149, in _handle
    return getattr(self,call)(args[1:])
  File "./src/omni.py", line 573, in listresources
    (rspecs, message) = self._listresources( args )
  File "./src/omni.py", line 336, in _listresources
    (ad_rspec_version, message) = self._get_advertised_rspecs(client)
  File "./src/omni.py", line 228, in _get_advertised_rspecs
    if not thisVersion.has_key('code'):
AttributeError: 'NoneType' object has no attribute 'has_key'
```

 _Imported from trac ticket [#131](http://trac.gpolab.bbn.com/gcf/ticket/131),  created by ahelsing on 04-24-2012 at 14:24, last modified: 05-07-2012 at 19:27_

**Comment by ahelsing** [comment]
Fixed: check for null version return from calling GetVersion
See commit [ddc59d0b6907e5e93c220b4403a67a4ba7511653](https://github.com/GENI-NSF/geni-tools/commit/ddc59d0b6907e5e93c220b4403a67a4ba7511653)


_Trac comment by ahelsing on 04-24-2012 at 14:25_
