### ISSUE TITLE
catch FOAM Protocol Error as not authorized

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#167]
The FOAM aggregate reports a ProtocolError if your credentials/certificate don't authorize you.
EG you use a non-trusted CH

Omni should catch these and report a more friendly error

 _Imported from trac ticket [#167](http://trac.gpolab.bbn.com/gcf/ticket/167),  created by ahelsing on 08-30-2012 at 08:31, last modified: 10-17-2014 at 15:32_

**Comment by ahelsing** [comment]
Sample error:
```
ERROR:omni.protogeni:Call for GetVersion at
 https://foam.gpolab.bbn.com:3626/foam/gapi/1 failed.: ProtocolError:
 <ProtocolError for foam.gpolab.bbn.com:3626/foam/gapi/1: 400 Bad Request>
 DEBUG:omni.protogeni:Traceback (most recent call last):
   File "/home/lnevers/gcf-2.0-rc1/src/omnilib/util/dossl.py", line 69, in
 _do_ssl
     result = fn(*args)
   File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in __call__
     return self.__send(self.__name, args)
   File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request
     verbose=self.__verbose
   File "/usr/lib/python2.6/xmlrpclib.py", line 1243, in request
     headers
 ProtocolError: <ProtocolError for foam.gpolab.bbn.com:3626/foam/gapi/1:
 400 Bad Request>
```


_Trac comment by ahelsing on 08-30-2012 at 08:32_

**Comment by tcmitchell** [comment]
Before enhancing omni to catch FOAM's ProtocolError we should learn more about FOAM's error handling. Does FOAM return ProtocolError only and always on authorization problems? Or on any malformed request (note: "400 Bad Request"). Is this actually a bug in FOAM, and not an authorization failure? Should FOAM be enhanced to return a more specific error on authorization failure?

If omni masks this error and assumes the problem is authorization failure, it may make it harder to debug a problem unrelated to authorization.

_Trac comment by tmitchel (github user: tcmitchell) on 08-30-2012 at 08:48_

**Comment by ahelsing** [comment]
https://openflow.stanford.edu/display/FOAM/FAQ has some more info about this, and other non-obvious errors.

This one is coming from nginx, the HTTP front end to FOAM, which is why FOAM doesn't (can't) give a more friendly message. There are probably other reasons why nginx might throw a 400 error, but this is definitely the most common.

If Omni could say something like "400 error -- often an authorization problem (is your cert signed by a non-trusted CH?)", so that it's suggesting the likely cause, but also exposing the actual error, that might be a good combination.

_Trac comment by jbs on 08-30-2012 at 09:06_

**Comment by tcmitchell** [comment]
If it's nginx that's reporting the error then credentials are not involved. This error is really about the certificate used to establish the SSL session.

Does that sound right?


_Trac comment by tmitchel (github user: tcmitchell) on 08-30-2012 at 09:17_

**Comment by ahelsing** [comment]
Replying to [tmitchel](comment:4):
> If it's nginx that's reporting the error then credentials are not involved. This error is really about the certificate used to establish the SSL session.
> 
> Does that sound right?

Ah, indeed, I was being fuzzy with terminology. That's exactly it, nginx is saying that the client SSL cert is not signed by a CA that nginx is configured to trust.

(So possibly some other SSL-related errors might also give a 400 error message; but in this case, it's about the signature on the client SL cert.)

_Trac comment by jbs on 08-30-2012 at 09:21_

**Comment by ahelsing** [comment]
I worry that other things might come through as a protocol error.

_Trac comment by ahelsing on 10-17-2014 at 15:32_
