### ISSUE TITLE
Name Error when there is an error creating a slice

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#192]
If there is an error when creating a slice, you get an ugly python error.

 _Imported from trac ticket [#192](http://trac.gpolab.bbn.com/gcf/ticket/192),  created by ahelsing on 09-17-2012 at 13:28, last modified: 09-17-2012 at 15:14_

**Comment by ahelsing** [comment]
```

lnevers@arendia:~/gcf-2.0-rc5$ omni.py createslice ahtest
INFO:omni:Loading config file /home/lnevers/.gcf/omni_config
INFO:omni:Using control framework emulab
ERROR:omni.protogeni:Failed to get credential for existing PG slice
urn:publicid:IDN+emulab.net+slice+ahtest: Not your slice! (code 3)
ERROR:omni:Create Slice Failed for slice name ahtest.
Traceback (most recent call last):
    File "/home/lnevers/gcf-2.0-rc5/src/omni.py", line 761, in <module>
      sys.exit(main())
    File "/home/lnevers/gcf-2.0-rc5/src/omni.py", line 755, in main
      API_call(framework, config, args, opts, verbose=opts.verbose)
    File "/home/lnevers/gcf-2.0-rc5/src/omni.py", line 440, in API_call
      result = handler._handle(args)
    File "/home/lnevers/gcf-2.0-rc5/src/omnilib/handler.py", line 78, in
_handle
      return getattr(self.chhandler, call)(args[1:])
    File "/home/lnevers/gcf-2.0-rc5/src/omnilib/chhandler.py", line 171,
in createslice
      if not self.logger.isEnabledFor(logging.DEBUG):
NameError: global name 'logging' is not defined
```


_Trac comment by ahelsing on 09-17-2012 at 13:29_
