### ISSUE TITLE
Sample myscript with options gives error on oddly formed results

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#193]
The included example of Omni scripting with options has a missing import, that causes an ugly stack trace if the Omni result is not formatted as it expects.
For example, calling a v1 aggregate.

 _Imported from trac ticket [#193](http://trac.gpolab.bbn.com/gcf/ticket/193),  created by ahelsing on 09-17-2012 at 13:31, last modified: 09-17-2012 at 16:02_

**Comment by ahelsing** [comment]
```
lnevers@arendia:~/gcf-2.0-rc5$ python examples/myscript.py -a
https://foam.gpolab.bbn.com:3626/foam/gapi/1 listresources -V1
Call Omni with args ['listresources']:

INFO:omni:Loading config file /home/lnevers/.gcf/omni_config
INFO:omni:Using control framework pg
INFO:omni:Listed resources on 1 out of 1 possible aggregates.
INFO:omni:<?xml version="1.0" ?>
INFO:omni:  <!-- Resources at AM:
      URN: unspecified_AM_URN
      URL: https://foam.gpolab.bbn.com:3626/foam/gapi/1
-->
INFO:omni:  <rspec type="advertisement"
xmlns="http://www.geni.net/resources/rspec/3"
xmlns:openflow="http://www.geni.net/resources/rspec/ext/openflow/3"
<<<<MANY LINES OF RESOURCES DELETED>>>> 

</rspec>

Got Result from Omni:

Traceback (most recent call last):
    File "examples/myscript.py", line 165, in <module>
      sys.exit(main())
    File "examples/myscript.py", line 150, in main
      print json.dumps(retItem, ensure_ascii=True, indent=2)
    File "/usr/lib/python2.6/json/__init__.py", line 237, in dumps
      **kw).encode(obj)
    File "/usr/lib/python2.6/json/encoder.py", line 367, in encode
      chunks = list(self.iterencode(o))
    File "/usr/lib/python2.6/json/encoder.py", line 309, in
_iterencode
      for chunk in self._iterencode_dict(o, markers):
    File "/usr/lib/python2.6/json/encoder.py", line 268, in
_iterencode_dict
      raise TypeError("key {0r} is not a string".format(key))
TypeError: key ('unspecified_AM_URN',
'https://foam.gpolab.bbn.com:3626/foam/gapi/1') is not a string
```


_Trac comment by ahelsing on 09-17-2012 at 13:32_
