### ISSUE TITLE
Handle better this exception

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#221]
I am at a seminar, so I haven't looked close to the error. I am creating the ticket so I don't forget to look into it. Here is a copy paste of the command and the error:
```
nriga@pella:~$ omni.py  --debug -a https://wings-openflow-1.wail.wisc.edu:12346/ listresources -V 1 -t ProtoGENI 2 -o
INFO:omni:Loading config file /home/nriga/.gcf/omni_config
INFO:omni:Using control framework pg
DEBUG:omni:Using framework type pg
DEBUG:omni.protogeni:Configured with key file /home/nriga/.ssl/geni_cert.pem
DEBUG:omni.protogeni:Using clearinghouse https://www.emulab.net:443/protogeni/xmlrpc/ch
DEBUG:omni.protogeni:Using slice authority https://www.pgeni.gpolab.bbn.com:443/protogeni/xmlrpc/sa
DEBUG:omni:User Cert File: /home/nriga/.ssl/geni_cert.pem
INFO:omni:Python: CPython 2.6.5
OS: Linux-2.6.32-42-generic-pae-i686-with-Ubuntu-10.04-lucid
Omni: GENI Omni Command Line Aggregate Manager Tool Version 2.2
Copyright (c) 2012 Raytheon BBN Technologies
DEBUG:omni:Read GetVersionCache from /home/nriga/.gcf/get_version_cache.json
DEBUG:omni:Checking cache for https://wings-openflow-1.wail.wisc.edu:12346/
DEBUG:omni:Actually calling GetVersion
ERROR:omni.protogeni:Call for GetVersion at https://wings-openflow-1.wail.wisc.edu:12346/ failed.: Unknown socket error: [Errno 111] Connection refused
DEBUG:omni.protogeni:Traceback (most recent call last):
  File "/home/nriga/gcf/src/omnilib/util/dossl.py", line 69, in _do_ssl
    result = fn(*args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.6/xmlrpclib.py", line 1235, in request
    self.send_content(h, request_body)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1349, in send_content
    connection.endheaders()
  File "/usr/lib/python2.6/httplib.py", line 904, in endheaders
    self._send_output()
  File "/usr/lib/python2.6/httplib.py", line 776, in _send_output
    self.send(msg)
  File "/usr/lib/python2.6/httplib.py", line 735, in send
    self.connect()
  File "/usr/lib/python2.6/httplib.py", line 1108, in connect
    sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/usr/lib/python2.6/socket.py", line 514, in create_connection
    raise error, msg
error: [Errno 111] Connection refused

DEBUG:omni:Added GetVersion error output to cache for https://wings-openflow-1.wail.wisc.edu:12346/: [Errno 111] Connection refused
DEBUG:omni:Wrote GetVersionCache to /home/nriga/.gcf/get_version_cache.json
WARNING:omni:Couldnt get api version supported from GetVersion: AM https://wings-openflow-1.wail.wisc.edu:12346/ failed getversion (empty): [Errno 111] Connection refused
DEBUG:omni:Checking cache for https://wings-openflow-1.wail.wisc.edu:12346/
DEBUG:omni:Actually calling GetVersion
ERROR:omni.protogeni:Call for GetVersion at https://wings-openflow-1.wail.wisc.edu:12346/ failed.: Unknown socket error: [Errno 111] Connection refused
DEBUG:omni.protogeni:Traceback (most recent call last):
  File "/home/nriga/gcf/src/omnilib/util/dossl.py", line 69, in _do_ssl
    result = fn(*args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.6/xmlrpclib.py", line 1235, in request
    self.send_content(h, request_body)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1349, in send_content
    connection.endheaders()
  File "/usr/lib/python2.6/httplib.py", line 904, in endheaders
    self._send_output()
  File "/usr/lib/python2.6/httplib.py", line 776, in _send_output
    self.send(msg)
  File "/usr/lib/python2.6/httplib.py", line 735, in send
    self.connect()
  File "/usr/lib/python2.6/httplib.py", line 1108, in connect
    sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/usr/lib/python2.6/socket.py", line 514, in create_connection
    raise error, msg
error: [Errno 111] Connection refused

DEBUG:omni:Added GetVersion error output to cache for https://wings-openflow-1.wail.wisc.edu:12346/: [Errno 111] Connection refused
DEBUG:omni:Wrote GetVersionCache to /home/nriga/.gcf/get_version_cache.json
DEBUG:omni:Checking cache for https://wings-openflow-1.wail.wisc.edu:12346/
DEBUG:omni:Actually calling GetVersion
ERROR:omni.protogeni:Call for GetVersion at https://wings-openflow-1.wail.wisc.edu:12346/ failed.: Unknown socket error: [Errno 111] Connection refused
DEBUG:omni.protogeni:Traceback (most recent call last):
  File "/home/nriga/gcf/src/omnilib/util/dossl.py", line 69, in _do_ssl
    result = fn(*args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.6/xmlrpclib.py", line 1235, in request
    self.send_content(h, request_body)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1349, in send_content
    connection.endheaders()
  File "/usr/lib/python2.6/httplib.py", line 904, in endheaders
    self._send_output()
  File "/usr/lib/python2.6/httplib.py", line 776, in _send_output
    self.send(msg)
  File "/usr/lib/python2.6/httplib.py", line 735, in send
    self.connect()
  File "/usr/lib/python2.6/httplib.py", line 1108, in connect
    sock = socket.create_connection((self.host, self.port), self.timeout)
  File "/usr/lib/python2.6/socket.py", line 514, in create_connection
    raise error, msg
error: [Errno 111] Connection refused

DEBUG:omni:Added GetVersion error output to cache for https://wings-openflow-1.wail.wisc.edu:12346/: [Errno 111] Connection refused
DEBUG:omni:Wrote GetVersionCache to /home/nriga/.gcf/get_version_cache.json
WARNING:omni:Couldnt get api versions supported from GetVersion: AM https://wings-openflow-1.wail.wisc.edu:12346/ failed getversion (empty): [Errno 111] Connection refused
WARNING:omni:You asked to use AM API 1, but the AM(s) you are contacting do not all speak that version.
Traceback (most recent call last):
  File "/home/nriga/gcf/src/omni.py", line 793, in <module>
    sys.exit(main())
  File "/home/nriga/gcf/src/omni.py", line 787, in main
    API_call(framework, config, args, opts, verbose=opts.verbose)
  File "/home/nriga/gcf/src/omni.py", line 456, in API_call
    result = handler._handle(args)
  File "/home/nriga/gcf/src/omnilib/handler.py", line 81, in _handle
    self.amhandler._correctAPIVersion(args)
  File "/home/nriga/gcf/src/omnilib/amhandler.py", line 134, in _correctAPIVersion
    newVer = int(liveVers.keys()[0])
ValueError: invalid literal for int() with base 10: 'None'
```

 _Imported from trac ticket [#221](http://trac.gpolab.bbn.com/gcf/ticket/221),  created by nriga on 12-10-2012 at 09:40, last modified: 12-12-2012 at 16:46_

**Comment by ahelsing** [comment]
The base error is that emulab is or was down.

At the end there's an error because it found no live AMs at all. I saw that bug last week, and have a fix for it.


_Trac comment by ahelsing on 12-10-2012 at 09:59_
