### ISSUE TITLE
omni says turn on debugging when debugging is turned on

### ISSUE THREAD

**Issue by tcmitchell** [GENI-NSF/geni-tools#30]
omni should detect that debug is enabled and not say "Please run --debug to see stack trace" if it is enabled.

Here is an example from an experimenter:
```
ERROR:omni:Error occurred. Unable to allocate from
https://www.emulab.net/protogeni/xmlrpc/am: <Fault 2: 'Could not map to
resources'>.  Please run --debug to see stack trace.
DEBUG:omni:Traceback (most recent call last):
 File "src/omni.py", line 322, in createsliver
   result = client.CreateSliver(urn, [slice_cred], rspec, slice_users)
 File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in __call__
   return self.__send(self.__name, args)
 File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request
   verbose=self.__verbose
 File "/usr/lib/python2.6/xmlrpclib.py", line 1253, in request
   return self._parse_response(h.getfile(), sock)
 File "/usr/lib/python2.6/xmlrpclib.py", line 1392, in _parse_response
   return u.close()
 File "/usr/lib/python2.6/xmlrpclib.py", line 838, in close
   raise Fault(**self._stack[0])
Fault: <Fault 2: 'Could not map to resources'>
```

 _Imported from trac ticket [#30](http://trac.gpolab.bbn.com/gcf/ticket/30),  created by tmitchel on 10-14-2010 at 10:17, last modified: 10-20-2010 at 15:05_

**Comment by ahelsing** [comment]
Fixed in HEAD
-- all traceback printouts are at DEBUG, and are all preceded by a message that only prints if DEBUG is not enabled, reminding the user to try running with --debug.



_Trac comment by ahelsing on 10-20-2010 at 12:45_
