### ISSUE TITLE
bug in clearpassphrases.py

### ISSUE THREAD

**Issue by innnkkki** [GENI-NSF/geni-tools#304]
Jeanne reports:
```

geni@GEC16-Tutorials:~/.gcf$ clear-passphrases.py
Traceback (most recent call last):
  File "/usr/local/bin/gcf/src/clear-passphrases.py", line 412, in <module>
    sys.exit(main())
  File "/usr/local/bin/gcf/src/clear-passphrases.py", line 396, in main
    setConfigFile(opts)
  File "/usr/local/bin/gcf/src/clear-passphrases.py", line 251, in setConfigFile
    opts.configfile = configile
NameError: global name 'configile' is not defined

I was able to work around it by fixing line 251. 
```

Need to take a look and fix it. 

 _Imported from trac ticket [#304](http://trac.gpolab.bbn.com/gcf/ticket/304),  created by nriga on 06-12-2013 at 14:38, last modified: 06-12-2013 at 17:28_
   CCing: johren@...

**Comment by innnkkki** [comment]
Fixed at [d41c5d1c25e0754fc6b4d7939f3ac7c03be25190](https://github.com/GENI-NSF/geni-tools/commit/d41c5d1c25e0754fc6b4d7939f3ac7c03be25190)



_Trac comment by nriga (github user: innnkkki) on 06-12-2013 at 14:46_
