### ISSUE TITLE
Stop common errors in framework_pgch.py from throwing a stacktrace

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#306]
A couple of calls generate stacktraces: 

```
$ omni.py -c ./omni_config-no-def-prj -o getslicecred lnportal
INFO:omni:Loading config file ./omni_config-no-def-prj
INFO:omni:Using control framework portal
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.3.2-rc1/src/omni.py", line 846, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.3.2-rc1/src/omni.py", line 833, in main
    API_call(framework, config, args, opts, verbose=opts.verbose)
  File "/home/lnevers/gcf-2.3.2-rc1/src/omni.py", line 464, in API_call
    result = handler._handle(args)
  File "/home/lnevers/gcf-2.3.2-rc1/src/omnilib/handler.py", line 78, in _handle
    return getattr(self.chhandler, call)(args[1:])
  File "/home/lnevers/gcf-2.3.2-rc1/src/omnilib/chhandler.py", line 448, in getslicecred
    urn = self.framework.slice_name_to_urn(name)
  File "/home/lnevers/gcf-2.3.2-rc1/src/omnilib/frameworks/framework_pgch.py", line 166, in slice_name_to_urn
    raise Exception("Invalid configuration: no default project defined")
Exception: Invalid configuration: no default project defined
```

And

```
$ ./src/omni.py -c ~/.gcf/omni_config.nye.nodefaultproject getslicecred urn:publicid:IDN+ch.geni.net:tutorial+user+test1 -o
INFO:omni:Loading config file /Users/sedwards/.gcf/omni_config.nye.nodefaultproject
INFO:omni:Using control framework portal
Traceback (most recent call last):
  File "./src/omni.py", line 846, in <module>
    sys.exit(main())
  File "./src/omni.py", line 833, in main
    API_call(framework, config, args, opts, verbose=opts.verbose)
  File "./src/omni.py", line 464, in API_call
    result = handler._handle(args)
  File "/Users/sedwards/projects/GENI/code/gcf/src/omnilib/handler.py", line 78, in _handle
    return getattr(self.chhandler, call)(args[1:])
  File "/Users/sedwards/projects/GENI/code/gcf/src/omnilib/chhandler.py", line 448, in getslicecred
    urn = self.framework.slice_name_to_urn(name)
  File "/Users/sedwards/projects/GENI/code/gcf/src/omnilib/frameworks/framework_pgch.py", line 152, in slice_name_to_urn
    raise Exception("Invalid Slice name: got a non Slice URN %s"% name)
Exception: Invalid Slice name: got a non Slice URN urn:publicid:IDN+ch.geni.net:tutorial+user+test1
```

Make them exit more cleanly.

 _Imported from trac ticket [#306](http://trac.gpolab.bbn.com/gcf/ticket/306),  created by sedwards on 06-14-2013 at 11:13, last modified: 06-14-2013 at 11:17_
   CCing: lnevers@...

**Comment by seledwards** [comment]
I change two places in the code to not raise an exception but instead to raise an OmniError and that seems to take care of it.

So now we get:
```
$ ./src/omni.py -c ~/.gcf/omni_config.nye.nodefaultproject getslicecred test1 -o
INFO:omni:Loading config file /Users/sedwards/.gcf/omni_config.nye.nodefaultproject
INFO:omni:Using control framework portal
ERROR:omni.pgch:Invalid configuration: no default project defined
Invalid configuration: no default project defined
```

And 
```
$ ./src/omni.py -c ~/.gcf/omni_config.nye.nodefaultproject getslicecred urn:publicid:IDN+ch.geni.net:tutorial+user+test1 -o
INFO:omni:Loading config file /Users/sedwards/.gcf/omni_config.nye.nodefaultproject
INFO:omni:Using control framework portal
ERROR:omni.pgch:Invalid Slice name: got a non Slice URN urn:publicid:IDN+ch.geni.net:tutorial+user+test1
Invalid Slice name: got a non Slice URN urn:publicid:IDN+ch.geni.net:tutorial+user+test1
```

This is in commit `1426e4eabed3611ba1889e636e5c84772a070f5e`.

_Trac comment by sedwards (github user: seledwards) on 06-14-2013 at 11:17_
