### ISSUE TITLE
stitcher: missing Document import

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#358]
stitcher objects.py is missing import of xml.dom.minidom.Document

Symptom:
```
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.4dev/src/stitcher.py", line 193, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.4dev/src/stitcher.py", line 174, in main
    text, item = call(argv)
  File "/home/lnevers/gcf-2.4dev/src/stitcher.py", line 165, in call
    return handler.doStitching(args)
  File "/home/lnevers/gcf-2.4dev/src/omnilib/stitchhandler.py", line 173, in doStitching
    lastAM = self.mainStitchingLoop(sliceurn, self.parsedUserRequest.dom)
  File "/home/lnevers/gcf-2.4dev/src/omnilib/stitchhandler.py", line 360, in mainStitchingLoop
    lastAM = launcher.launch(self.parsedSCSRSpec, self.scsCalls)
  File "/home/lnevers/gcf-2.4dev/src/omnilib/stitch/launcher.py", line 51, in launch
    agg.allocate(self.opts, self.slicename, rspec.dom, scsCallCount)
  File "/home/lnevers/gcf-2.4dev/src/omnilib/stitch/objects.py", line 387, in allocate
    self.requestDom = self.getEditedRSpecDom(rspecDom)
  File "/home/lnevers/gcf-2.4dev/src/omnilib/stitch/objects.py", line 671, in getEditedRSpecDom
    path.editChangesIntoDom(domNode)
  File "/home/lnevers/gcf-2.4dev/src/omnilib/stitch/objects.py", line 147, in editChangesIntoDom
    hop.editChangesIntoDom(domHopNode)
  File "/home/lnevers/gcf-2.4dev/src/omnilib/stitch/objects.py", line 2020, in editChangesIntoDom
    self._hop_link.editChangesIntoDom(child)
  File "/home/lnevers/gcf-2.4dev/src/omnilib/stitch/objects.py", line 2280, in editChangesIntoDom
vlan_range[0].appendChild(Document.createTextNode(newVlanRangeString))
NameError: global name 'Document' is not defined

```

 _Imported from trac ticket [#358](http://trac.gpolab.bbn.com/gcf/ticket/358),  created by ahelsing on 09-05-2013 at 14:22, last modified: 09-05-2013 at 15:46_

**Comment by ahelsing** [comment]
actual fix is to change calls to node.ownerDocument....

_Trac comment by ahelsing on 09-05-2013 at 15:46_
