### ISSUE TITLE
acceptance tests must handle AMs that wont renew slivers shorter

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#369]
AMs get to decide the initial sliver lifetime. And the AM API allows an AM to refuse to renew a sliver to a time earlier than its current expiration.
Instageni / Protogeni allow it. Exogeni does not.

And apparently the default Exogeni sliver life is > 2 days.

So really we want the acceptance tests to pick a sliver renewal time that is past the current expiration. Or maybe 1 before (and allow that to fail) and 1 after?

This is a little more complicated in that it means you have to find the expiration time of the slivers at the AM.
At PG/IG, there is the `pg_expires` in `sliverstatus`.
At EG there is `orca_expires`

Sample behavior on error:
 ```
 Traceback (most recent call last):
   File "./am_api_accept.py", line 771, in test_CreateSliver
     self.subtest_CreateSliverWorkflow()
   File "./am_api_accept.py", line 927, in subtest_CreateSliverWorkflow
     self.subtest_generic_RenewSliver_many( slicename )
   File "./am_api_accept.py", line 1931, in
 subtest_generic_RenewSliver_many
     self.subtest_RenewSliver_many( slicename )
   File "./am_api_accept.py", line 1408, in subtest_RenewSliver_many
     self.subtest_RenewSliver( slicename, twodays )
   File "./am_api_accept.py", line 1373, in subtest_RenewSliver
     text, (succList, failList) = self.call(omniargs, self.options_copy)
   File "/home/lnevers/gcf-2.4-rc3/src/omni_unittest.py", line 171, in call
     ret_val = omni.call( cmd, options=options, verbose=True )
   File "/home/lnevers/gcf-2.4-rc3/src/omni.py", line 575, in call
     return API_call( framework, config, args, opts, verbose=verbose )
   File "/home/lnevers/gcf-2.4-rc3/src/omni.py", line 595, in API_call
     result = handler._handle(args)
   File "/home/lnevers/gcf-2.4-rc3/src/omnilib/handler.py", line 83, in
 _handle
     (message, val) = getattr(self.amhandler,call)(args[1:])
   File "/home/lnevers/gcf-2.4-rc3/src/omnilib/amhandler.py", line 2531, in
 renewsliver
     (res, message) = self._retrieve_value(res, message, self.framework)
   File "/home/lnevers/gcf-2.4-rc3/src/omnilib/amhandler.py", line 4197, in
 _retrieve_value
     self._raise_omni_error(message, AMAPIError, result)
   File "/home/lnevers/gcf-2.4-rc3/src/omnilib/amhandler.py", line 4294, in
 _raise_omni_error
     raise err, (msg, triple)
 AMAPIError: AMAPIError: Error from Aggregate: code 1: renewSlice():
 renewal term shorter than original slice end is not valid..
 ```
 Acceptance test logs show the attempt to renew to shorter term:
 ```
 INFO:2013-09-12 09:15:52,613: handler_utils.py#_derefAggNick():61:
 Substituting AM nickname am-undertest with URL https://bbn-
 hn.exogeni.net:11443/orca/xmlrpc, URN unspecified_AM_URN
 INFO:2013-09-12 09:15:53,536:
 handler_utils.py#_print_slice_expiration():254: Slice
 urn:publicid:IDN+ch.geni.net:ln-prj+slice+acclne-131307 expires on
 2013-09-19 13:13:08 UTC
 INFO:2013-09-12 09:15:53,537: amhandler.py#renewsliver():2493: Renewing
 Sliver acclne-131307 until 2013-09-14 13:15:21+00:00 (UTC)
 ERROR:2013-09-12 09:15:53,830: amhandler.py#_raise_omni_error():4290:
 {'output': 'renewSlice(): renewal term shorter than original slice end is
 not valid.', 'code': {'geni_code': 1}}
 INFO:2013-09-12 09:16:23,845:
 am_api_accept.py#subtest_DeleteSliver():1750:
 ```

 _Imported from trac ticket [#369](http://trac.gpolab.bbn.com/gcf/ticket/369),  created by ahelsing on 09-12-2013 at 15:27, last modified: 10-17-2014 at 15:11_

**Comment by ahelsing** [comment]
Sample status from EG:
```
{
  "geni_status": "ready", 
  "geni_urn": "urn:publicid:IDN+ch.geni.net:ahscaletest+slice+ahtest", 
  "geni_resources": [
    {
      "orca_expires": "Wed Sep 18 14:32:29 UTC 2013", 
      "geni_urn": "urn:publicid:IDN+exogeni.net:bbnvmsite+sliver+9cbad8a1-82c9-4523-b38b-98809f84f905:VM", 
      "geni_error": "", 
      "geni_status": "ready"
    }
  ]
}
```


_Trac comment by ahelsing on 09-12-2013 at 15:30_

**Comment by ahelsing** [comment]
Sample status from PG:
```
{
  "users": [
    {
      "keys": [
        {
          "type": "ssh", 
          "key": "ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAwhxWkZuS20ow0MnVeSiiRar55Qgy1GA74HIxgiMSPiqQEL3fjufyO/g6FK7R659oNQRbvLlrN5zpaDQ4MBk/JLTt6NO+9IUsB6HlI2P5q8bVyRpUf6E3SJh2iZWQCLDheyBk1+SjJsmH8ovjrWpfZuABIHYaH2gc3hy0igXiaYeYAF8jH8G+cmDcjd2+lQDwi7PhyOxM5Ai4u+kw16su1HFXBNkDZ0e7+YtPVElDC4TCBmt0O98gPVjcIsD1pDgSbdsTZe6zqLBgujrPQhC72eADtoi3WCMiyo+GPEPeYRrZo4H9vSt2pdIg9E73wJPgCu/LcAql2FJh/glsIqpIhw== ahelsing@hotcocoa2"
        }
      ], 
      "urn": "urn:publicid:IDN+ch.geni.net+user+ahelsing", 
      "login": "ahelsing"
    }
  ], 
  "pg_status": "ready", 
  "geni_status": "ready", 
  "geni_urn": "urn:publicid:IDN+ch.geni.net:ahscaletest+slice+ahtest", 
  "geni_resources": [
    {
      "pg_status": "ready", 
      "geni_urn": "urn:publicid:IDN+instageni.gpolab.bbn.com+sliver+11729", 
      "pg_manifest": {
        "attributes": {
          "exclusive": "false", 
          "xmlns": "http://www.geni.net/resources/rspec/3", 
          "sliver_id": "urn:publicid:IDN+instageni.gpolab.bbn.com+sliver+11729", 
          "component_id": "urn:publicid:IDN+instageni.gpolab.bbn.com+node+pc1", 
          "client_id": "request1", 
          "component_manager_id": "urn:publicid:IDN+instageni.gpolab.bbn.com+authority+cm"
        }, 
        "name": "node", 
        "children": [
          {
            "attributes": {
              "name": "emulab-openvz"
            }, 
            "name": "sliver_type", 
            "children": []
          }, 
          {
            "attributes": {
              "name": "pcvm1-24", 
              "xmlns:rs": "http://www.protogeni.net/resources/rspec/ext/emulab/1"
            }, 
            "name": "rs:vnode", 
            "children": []
          }, 
          {
            "attributes": {
              "name": "request1.ahtest.ch-geni-net.instageni.gpolab.bbn.com"
            }, 
            "name": "host", 
            "children": []
          }, 
          {
            "attributes": {}, 
            "name": "services", 
            "children": [
              {
                "attributes": {
                  "username": "ahelsing", 
                  "authentication": "ssh-keys", 
                  "hostname": "pc1.instageni.gpolab.bbn.com", 
                  "port": "30266"
                }, 
                "name": "login", 
                "children": []
              }
            ]
          }
        ]
      }, 
      "geni_error": "", 
      "geni_status": "ready"
    }
  ], 
  "pg_expires": "2013-09-17T00:00:00", 
  "pg_public_url": "https://boss.instageni.gpolab.bbn.com/showslicepub.php?publicid=cafb5549ecbea2121858cc14aa5a3e97"
}
```


_Trac comment by ahelsing on 09-12-2013 at 15:31_

**Comment by ahelsing** [comment]
See ticket #188

_Trac comment by ahelsing on 09-13-2013 at 10:32_
