### ISSUE TITLE
Support SFA record structure changing

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#429]
Tony asked us to test a new version of their AM API v2 implementation.

In this version, the user and slice records are structured a little different. In particular, keys is now reg-keys, and slices is now reg-slices. slice_ids and key_ids are gone.

 _Imported from trac ticket [#429](http://trac.gpolab.bbn.com/gcf/ticket/429),  created by ahelsing on 11-12-2013 at 16:34, last modified: 02-14-2014 at 09:00_

**Comment by luisanevers** [comment]
I just got a chance to try the SFA V2 and tried a listresources, which just hang:
```
$ omni.py listresources -a plc2 --debug
16:48:17 INFO     omni: Using control framework plc
16:48:17 DEBUG    omni: Using framework type sfa
16:48:17 INFO     omni.sfa: SFA Registry: https://sfav2.planet-lab.org:12345
16:48:17 INFO     omni.sfa: SFA Slice Manager: https://sfav2.planet-lab.org:12347
16:48:17 DEBUG    omni: User Cert File: /home/lnevers/.gcf/plc.bbn.luisa_nevers.gid
16:48:17 INFO     omni: Python: CPython 2.6.5
OS: Linux-2.6.32-55-generic-pae-i686-with-Ubuntu-10.04-lucid
Omni: GENI Omni Command Line Aggregate Manager Tool Version 2.5
Copyright (c) 2014 Raytheon BBN Technologies
16:48:17 INFO     omni: Substituting AM nickname plc2 with URL https://sfav2.planet-lab.org:12346, URN unspecified_AM_URN
16:48:17 DEBUG    omni: Read GetVersionCache from /home/lnevers/.gcf/get_version_cache.json
16:48:17 DEBUG    omni: Checking cache for https://sfav2.planet-lab.org:12346
16:48:17 DEBUG    omni: Actually calling GetVersion
16:48:17 DEBUG    omni:  ... cachedVersion was None
<<<<HANG>>>
```



_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 16:52_

**Comment by luisanevers** [comment]
The hangs that was captured in yesterday's update actually times out 6 minutes later.  Below is the full output for the failed AM API call to the SFA v2:
```
$ omni.py listresources -a https://sfav2.planet-lab.org:12346 --debug
08:49:35 INFO     omni: Loading agg_nick_cache file '/home/lnevers/.gcf/agg_nick_cache'
08:49:35 INFO     omni: Loading config file /home/lnevers/.gcf/omni_config
08:49:35 INFO     omni: Using control framework portal
08:49:35 DEBUG    omni: Using framework type pgch
08:49:35 DEBUG    omni.protogeni: Configured with key file /home/lnevers/.ssl/geni_cert_portal.pem
08:49:35 DEBUG    omni.protogeni: Using clearinghouse https://ch.geni.net/PGCH
08:49:35 DEBUG    omni.protogeni: Using slice authority https://ch.geni.net/PGCH
08:49:35 DEBUG    omni: User Cert File: /home/lnevers/.ssl/geni_cert_portal.pem
08:49:35 INFO     omni: Python: CPython 2.6.5
OS: Linux-2.6.32-55-generic-pae-i686-with-Ubuntu-10.04-lucid
Omni: GENI Omni Command Line Aggregate Manager Tool Version 2.5
Copyright (c) 2014 Raytheon BBN Technologies
08:49:35 DEBUG    omni: Read GetVersionCache from /home/lnevers/.gcf/get_version_cache.json
08:49:35 DEBUG    omni: Checking cache for https://sfav2.planet-lab.org:12346
08:49:35 DEBUG    omni: Actually calling GetVersion
08:49:35 DEBUG    omni:  ... cachedVersion was None08:55:35 
ERROR    omni.pgch: Call for Check AM properties at https://sfav2.planet-lab.org:12346 failed.: 
Unknown SSL error: The read operation timed out
08:55:35 DEBUG    omni.pgch: Traceback (most recent call last):
  File "/home/lnevers/gcf-2.5-021314/src/gcf/omnilib/util/dossl.py", line 70, in _do_ssl
    result = fn(*args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1199, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1489, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.6/xmlrpclib.py", line 1253, in request
    return self._parse_response(h.getfile(), sock)
  File "/usr/lib/python2.6/xmlrpclib.py", line 1382, in _parse_response
    response = file.read(1024)
  File "/usr/lib/python2.6/socket.py", line 353, in read
    data = self._sock.recv(left)
  File "/usr/lib/python2.6/ssl.py", line 96, in <lambda>
    self.recv = lambda buflen=1024, flags=0: SSLSocket.recv(self, buflen, flags)
  File "/usr/lib/python2.6/ssl.py", line 222, in recv
    raise x
SSLError: The read operation timed out

08:55:35 DEBUG    omni: Added GetVersion error output to cache for https://sfav2.planet-lab.org:12346: Unknown SSL error: The read operation timed out
08:55:35 DEBUG    omni: Wrote GetVersionCache to /home/lnevers/.gcf/get_version_cache.json
08:55:35 DEBUG    omni: Couldn't get api version supported from GetVersion: AM https://sfav2.planet-lab.org:12346 failed getversion (empty): Unknown SSL error: The read operation timed out
08:55:35 ERROR    omni: AM https://sfav2.planet-lab.org:12346 failed getversion (empty): Unknown SSL error: The read operation timed out
AM https://sfav2.planet-lab.org:12346 failed getversion (empty): Unknown SSL error: The read operation timed out
```

_Trac comment by lnevers (github user: luisanevers) on 02-14-2014 at 09:00_
