### ISSUE TITLE
listimages fails to handler errors

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#437]
```
$ omni.py listimages -a utah-ig urn:publicid:IDN+emulab.net+user+stroller
09:40:26 INFO     omni: Loading agg_nick_cache file '/home/lnevers/.gcf/agg_nick_cache'
09:40:26 INFO     omni: Loading config file /home/lnevers/.gcf/omni_config
09:40:26 INFO     omni: Using control framework portal
09:40:26 INFO     omni: Substituting AM nickname utah-ig with URL https://boss.utah.geniracks.net:12369/protogeni/xmlrpc/am/2.0, URN urn:publicid:IDN+utah.geniracks.net+authority+cm
09:40:26 INFO     omni: ListImages got creator_urn 'urn:publicid:IDN+emulab.net+user+stroller'
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.4.1/src/omni.py", line 1074, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.4.1/src/omni.py", line 1061, in main
    API_call(framework, config, args, opts, verbose=opts.verbose)
  File "/home/lnevers/gcf-2.4.1/src/omni.py", line 601, in API_call
    result = handler._handle(args)
  File "/home/lnevers/gcf-2.4.1/src/omnilib/handler.py", line 84, in _handle
    return (msg+message, val)
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

 _Imported from trac ticket [#437](http://trac.gpolab.bbn.com/gcf/ticket/437),  created by ahelsing on 11-20-2013 at 10:28, last modified: 02-13-2014 at 09:43_

**Comment by ahelsing** [comment]
2 issues here: 

1) The handler's `_handle()` method needs to handle if the message is None
2) `listimages` and `deleteimage` return the message and struct in the wrong order on error


_Trac comment by ahelsing on 11-20-2013 at 10:29_

**Comment by luisanevers** [comment]
Using gcf-2.5-021214pm, verified listimages wit user URN can now handle "None" as a return:
```
$ omni.py listimages -a utah-ig urn:publicid:IDN+emulab.net+user+stroller 
09:39:03 INFO     omni: Loading agg_nick_cache file '/home/lnevers/.gcf/agg_nick_cache'
09:39:03 INFO     omni: Loading config file /home/lnevers/.gcf/omni_config
09:39:03 INFO     omni: Using control framework portal
09:39:03 INFO     omni: Substituting AM nickname utah-ig with URL https://boss.utah.geniracks.net:12369/protogeni/xmlrpc/am/2.0, URN urn:publicid:IDN+utah.geniracks.net+authority+cm
09:39:03 INFO     omni: ListImages got creator_urn 'urn:publicid:IDN+emulab.net+user+stroller'
09:39:03 INFO     omni:  ------------------------------------------------------
09:39:03 INFO     omni:  Completed listimages:
Args: listimages urn:publicid:IDN+emulab.net+user+stroller

  Result Summary: Cannot listimages: Given creator urn:publicid:IDN+emulab.net+user+stroller not from same SA as you (ch.geni.net) 
09:39:03 INFO     omni:  ======================================================
```
Also verified that listimages and deleteimages still work as expected.



_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 09:43_
