### ISSUE TITLE
Valid URNs should have 3 + separated pieces

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#483]
The URN validity test doesn't check that we have multiple pieces separated by a `+` and it should.

Add that test.

 _Imported from trac ticket [#483](http://trac.gpolab.bbn.com/gcf/ticket/483),  created by ahelsing on 02-03-2014 at 16:00, last modified: 02-13-2014 at 13:17_

**Comment by ahelsing** [comment]
added to `is_valid_urn` in `urn_utils`.

_Trac comment by ahelsing on 02-03-2014 at 16:01_

**Comment by luisanevers** [comment]
Verified that specifying an invalid user URN is now handled and generates:
```
13:16:21 ERROR    omni: Creator URN invalid: urn:publicid:IDN.ch.geni.net+user.lnevers
Creator URN invalid: urn:publicid:IDN.ch.geni.net+user.lnevers
```

Rather than the old failure:
```
13:17:06 INFO     omni: ListImages got creator_urn 'urn:publicid:IDN.ch.geni.net+user.lnevers'
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.4.1/src/omni.py", line 1074, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.4.1/src/omni.py", line 1061, in main
    API_call(framework, config, args, opts, verbose=opts.verbose)
  File "/home/lnevers/gcf-2.4.1/src/omni.py", line 601, in API_call
    result = handler._handle(args)
  File "/home/lnevers/gcf-2.4.1/src/omnilib/handler.py", line 83, in _handle
    (message, val) = getattr(self.amhandler,call)(args[1:])
  File "/home/lnevers/gcf-2.4.1/src/omnilib/amhandler.py", line 3839, in listimages
    if creator_urn and not urn_util.is_valid_urn_bytype(creator_urn, 'user', self.logger):
  File "/home/lnevers/gcf-2.4.1/src/geni/util/urn_util.py", line 160, in is_valid_urn_bytype
    urnObj = URN(urn=inurn)
  File "/home/lnevers/gcf-2.4.1/src/geni/util/urn_util.py", line 61, in __init__
    self.type = urn_to_string_format(spl[2])
IndexError: list index out of range
```

_Trac comment by lnevers (github user: luisanevers) on 02-13-2014 at 13:17_
