### ISSUE TITLE
readyToLogin gives errors at ION

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#536]
running readyToLogin on a stitched slice with resources at ION gives errors.

```
 $ readyToLogin.py IG-ST-1 --useSliceAggregates
 Key file [/home/lnevers/.ssh/niky-geni_key] does NOT exist.
 Traceback (most recent call last):
   File "/home/lnevers/gcf-2.5-rc1/examples/readyToLogin.py", line 899, in
 <module>
     sys.exit(main())
   File "/home/lnevers/gcf-2.5-rc1/examples/readyToLogin.py", line 886, in
 main
     loginInfoDict, keyList = main_no_print(argv=argv)
   File "/home/lnevers/gcf-2.5-rc1/examples/readyToLogin.py", line 862, in
 main_no_print
     amLoginInfo = getInfoFromSliverStatus(amUrl, amType)
   File "/home/lnevers/gcf-2.5-rc1/examples/readyToLogin.py", line 380, in
 getInfoFromSliverStatus
     loginInfo = getInfoFromSliverStatusPL(sliverStatus[amUrl])
   File "/home/lnevers/gcf-2.5-rc1/examples/readyToLogin.py", line 315, in
 getInfoFromSliverStatusPL
     if (not sliverStat['pl_login']) or (not resourceDict['pl_hostname']):
 KeyError: 'pl_login'
 ```

 The list of slivers associated with the slice IG-ST-1 includes:
 ```
 $ omni.py listslivers IG-ST-1
 12:14:01 INFO     omni: Loading agg_nick_cache file
 '/home/lnevers/.gcf/agg_nick_cache'
 12:14:01 INFO     omni: Loading config file /home/lnevers/.gcf/omni_config
 12:14:01 INFO     omni: Using control framework my_chapi
 12:14:01 INFO     omni: Member Authority is https://ch.geni.net/MA (from
 config)
 12:14:01 INFO     omni: Slice Authority is https://ch.geni.net/SA (from
 config)
 12:14:02 INFO     omni:
 ------------------------------------------------------
 12:14:02 INFO     omni:  Completed listslivers:
 Args: listslivers IG-ST-1

   Result Summary: Slivers by aggregate for slice
 urn:publicid:IDN+ch.geni.net:ln-prj+slice+IG-ST-1

 Aggregate: urn:publicid:IDN+ion.internet2.edu+authority+am ( ion )
     Sliver:
 urn:publicid:IDN+ion.internet2.edu+sliver+ion.internet2.edu-70801 expires
 on 2014-03-04 17:03:29 UTC

 Aggregate: urn:publicid:IDN+instageni.gpolab.bbn.com+authority+cm ( gpo-ig
 )
     Sliver: urn:publicid:IDN+instageni.gpolab.bbn.com+sliver+29131 expires
 on 2014-03-04 17:03:29 UTC
     Sliver: urn:publicid:IDN+instageni.gpolab.bbn.com+sliver+29130 expires
 on 2014-03-04 17:03:29 UTC
     Sliver: urn:publicid:IDN+instageni.gpolab.bbn.com+sliver+29128 expires
 on 2014-03-04 17:03:29 UTC

 Aggregate: urn:publicid:IDN+instageni.stanford.edu+authority+cm (
 stanford-ig )
     Sliver: urn:publicid:IDN+instageni.stanford.edu+sliver+612 expires on
 2014-03-04 17:03:29 UTC
     Sliver: urn:publicid:IDN+instageni.stanford.edu+sliver+609 expires on
 2014-03-04 17:03:29 UTC
     Sliver: urn:publicid:IDN+instageni.stanford.edu+sliver+611 expires on
 2014-03-04 17:03:29 UTC

 12:14:02 INFO     omni:
 ======================================================
 ```

 _Imported from trac ticket [#536](http://trac.gpolab.bbn.com/gcf/ticket/536),  created by ahelsing on 02-25-2014 at 12:28, last modified: 02-25-2014 at 12:46_

**Comment by ahelsing** [comment]
Need to bail on SFA based AMs that have no nodes reserved earlier.

_Trac comment by ahelsing on 02-25-2014 at 12:46_
