### ISSUE TITLE
stitcher: Support output files in temp files

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#588]
For stitcher to run behind a server like the portal, it needs to support multiple instances in parallel for different users, where the unix user it is running as has not home directory, and the current working is not writable.

Refactor output file generation so all files can go in a named directory or in /tmp. Consider having all files be temp files in some mode.

 _Imported from trac ticket [#588](http://trac.gpolab.bbn.com/gcf/ticket/588),  created by ahelsing on 04-02-2014 at 14:23, last modified: 05-23-2014 at 10:34_

**Comment by ahelsing** [comment]
Luisa found an example of what happens without this fix:
```
Traceback (most recent call last):
   File "/home/lnevers1/gcf-2.6-pre04292/src/stitcher.py", line 199, in <module>
     sys.exit(main())
   File "/home/lnevers1/gcf-2.6-pre04292/src/stitcher.py", line 180, in main
     text, item = call(argv)
   File "/home/lnevers1/gcf-2.6-pre04292/src/stitcher.py", line 171, in call
     return handler.doStitching(args)
   File "/home/lnevers1/gcf-2.6-pre04292/src/gcf/omnilib/stitchhandler.py", line 204, in doStitching
     lastAM = self.mainStitchingLoop(sliceurn, self.parsedUserRequest.getLinkEditedDom())
   File "/home/lnevers1/gcf-2.6-pre04292/src/gcf/omnilib/stitchhandler.py", line 556, in mainStitchingLoop
     lastAM = launcher.launch(self.parsedSCSRSpec, self.scsCalls)
   File "/home/lnevers1/gcf-2.6-pre04292/src/gcf/omnilib/stitch/launcher.py", line 53, in launch
     agg.allocate(self.opts, self.slicename, rspec.dom, scsCallCount)
   File "/home/lnevers1/gcf-2.6-pre04292/src/gcf/omnilib/stitch/objects.py", line 441, in allocate
     manifestString = self.doReservation(opts, slicename, scsCallCount)
   File "/home/lnevers1/gcf-2.6-pre04292/src/gcf/omnilib/stitch/objects.py", line 1000, in doReservation
     _printResults(opts_copy, self.logger, header, content, self.rspecfileName)
   File "/home/lnevers1/gcf-2.6-pre04292/src/gcf/omnilib/util/handler_utils.py", line 748, in _printResults
     with open(filename,'w') as file:

```

_Trac comment by ahelsing on 05-15-2014 at 11:55_

**Comment by ahelsing** [comment]
In Luisa's case there, the file in question already existed and was owned by a different user.

_Trac comment by ahelsing on 05-15-2014 at 11:57_

**Comment by ahelsing** [comment]
Adding a new option --filePrefix. This goes in the front of any path for a stitcher output file. If it includes a directory, it replaces the directory otherwise used (like /tmp and ~/.gcf). It also is merged with any value in --prefix.


_Trac comment by ahelsing on 05-22-2014 at 15:14_

**Comment by ahelsing** [comment]
renamed it fileDir and it is strictly a directory

_Trac comment by ahelsing on 05-23-2014 at 10:34_
