### ISSUE TITLE
readyToLogin.py reports exception

### ISSUE THREAD

**Issue by seledwards** [GENI-NSF/geni-tools#599]
I'm seeing an error similar to #399 after calling `geni_reload` at IG:
```
$ readyToLogin.py -a utah-ig urn:publicid:IDN+ch.geni.net:tutorial+slice+test
Traceback (most recent call last):
  File "/Users/sedwards/projects/GENI/code/gcf/examples/readyToLogin.py", line 902, in <module>
    sys.exit(main())
  File "/Users/sedwards/projects/GENI/code/gcf/examples/readyToLogin.py", line 889, in main
    loginInfoDict, keyList = main_no_print(argv=argv)
  File "/Users/sedwards/projects/GENI/code/gcf/examples/readyToLogin.py", line 877, in main_no_print
    amLoginInfo = addNodeStatus(amUrl, amType, amLoginInfo)
  File "/Users/sedwards/projects/GENI/code/gcf/examples/readyToLogin.py", line 476, in addNodeStatus
    amLoginInfo = addNodeStatusPG( amLoginInfo, amSliverStat )
  File "/Users/sedwards/projects/GENI/code/gcf/examples/readyToLogin.py", line 488, in addNodeStatusPG
    for resourceDict in amSliverStat['geni_resources']:
TypeError: 'bool' object has no attribute '__getitem__'
```

 _Imported from trac ticket [#599](http://trac.gpolab.bbn.com/gcf/ticket/599),  created by sedwards on 04-16-2014 at 15:33, last modified: 06-03-2014 at 10:58_

**Comment by ahelsing** [comment]
adding logic to check for malformed struct before trying to parse it. This still doesn't explain why the return from sliverstatus was malformed though.

_Trac comment by ahelsing on 06-03-2014 at 10:56_
