### ISSUE TITLE
GRAM AMs skip nodes in manifest; combined manifest suffers

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#605]
GRAM AMs only list nodes/links that they are involved with. So if we use the GRAM AM as the base in the manifest rspec combiner, then we need to carefully add in any links/nodes with a client_id that is not in the base.

 _Imported from trac ticket [#605](http://trac.gpolab.bbn.com/gcf/ticket/605),  created by ahelsing on 04-29-2014 at 14:39, last modified: 06-03-2014 at 14:24_

**Comment by ahelsing** [comment]
GRAM is losing interface_ref and component_manager sub elements of links. But the nodes and links are now all in the manifest. Put that remaining issue in ticket #607.

_Trac comment by ahelsing on 05-02-2014 at 14:42_

**Comment by luisanevers** [comment]
The "fileDir" option does not handle lack of for the specified path:
```
$ stitcher createsliver lngre --fileDir /tmp/nopriv --prefix mypref IG-CT-3-nps.rspec 
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.6-rc1/src/stitcher.py", line 301, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.6-rc1/src/stitcher.py", line 282, in main
    text, item = call(argv)
  File "/home/lnevers/gcf-2.6-rc1/src/stitcher.py", line 187, in call
    omni.configure_logging(options)
  File "/home/lnevers/gcf-2.6-rc1/src/gcf/oscript.py", line 818, in configure_logging
    applyLogConfig(opts.logconfig, defaults=deft)
  File "/home/lnevers/gcf-2.6-rc1/src/gcf/oscript.py", line 869, in applyLogConfig
    logging.config.fileConfig(fn, defaults=defaults, disable_existing_loggers=False)
  File "/usr/lib/python2.7/logging/config.py", line 78, in fileConfig
    handlers = _install_handlers(cp, formatters)
  File "/usr/lib/python2.7/logging/config.py", line 156, in _install_handlers
    h = klass(*args)
  File "/usr/lib/python2.7/logging/__init__.py", line 897, in __init__
    StreamHandler.__init__(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 916, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 13] Permission denied: '/tmp/nopriv/stitcher.log'
$ 
```

_Trac comment by lnevers (github user: luisanevers) on 06-03-2014 at 14:12_

**Comment by luisanevers** [comment]
The previous message was meant for ticket http://groups.geni.net/syseng/ticket/6149. 
Pasted in wrong tab. Please ignore the previous note.

_Trac comment by lnevers (github user: luisanevers) on 06-03-2014 at 14:24_
