### ISSUE TITLE
EG sometimes omits 'state' from manifest, breaking readyToLogin

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#636]
It appears that sometimes EG AMs omit the 'state' attribute from the `geni_sliver_info` element. This breaks readyToLogin.

```
$ readyToLogin EG-CT-2-fiu -a fiu-eg
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.6-rc2/examples/readyToLogin.py", line 905, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.6-rc2/examples/readyToLogin.py", line 892, in main
    loginInfoDict, keyList = main_no_print(argv=argv)
  File "/home/lnevers/gcf-2.6-rc2/examples/readyToLogin.py", line 876, in main_no_print
    amLoginInfo = getInfoFromSliceManifest(amUrl)
  File "/home/lnevers/gcf-2.6-rc2/examples/readyToLogin.py", line 226, in getInfoFromSliceManifest
    maniInfo = getInfoFromManifest(manifest)
  File "/home/lnevers/gcf-2.6-rc2/examples/readyToLogin.py", line 136, in getInfoFromManifest
    geni_status = gsi_el.attrib['state']
KeyError: 'state'
```

See the manifest RSpec here:
http://groups.geni.net/syseng/attachment/ticket/6149/EG-CT-2-manifest-rspec-exogeni-net-fiuvmsite.xml

And status:
http://groups.geni.net/syseng/attachment/ticket/6149/EG-CT-2-sliverstatus-exogeni-net-fiuvmsite.json

 _Imported from trac ticket [#636](http://trac.gpolab.bbn.com/gcf/ticket/636),  created by ahelsing on 06-04-2014 at 15:05, last modified: 06-04-2014 at 15:47_

**Comment by ahelsing** [comment]
Adding logic to be robust to that attribute missing.

_Trac comment by ahelsing on 06-04-2014 at 15:47_
