### ISSUE TITLE
readyToLogin fails in APIv3 when AM gives an error return

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#707]
When using readyToLogin and AM API v3, if the AM gives an error in the return from describe, readyToLogin gives an error:
```
$ readyToLogin -a stanford-ig3 al2s-perf -V3
Key file [/home/lnevers/.ssh/arendia-id_rsa] does NOT exist.
Key file [/home/lnevers/.ssh/sendaria-id_rsa] does NOT exist.
16:15:16 WARNING : Got no resource listing from AM stanford-ig3
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.7-rc2/examples/readyToLogin.py", line 818, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.7-rc2/examples/readyToLogin.py", line 805, in main
    loginInfoDict, keyList = main_no_print(argv=argv)
  File "/home/lnevers/gcf-2.7-rc2/examples/readyToLogin.py", line 789, in main_no_print
    amLoginInfo = getInfoFromSliceManifest(amUrl)
  File "/home/lnevers/gcf-2.7-rc2/examples/readyToLogin.py", line 226, in getInfoFromSliceManifest
    manifest = value['geni_rspec']
TypeError: 'int' object is unsubscriptable
```

The code does not check for a non 0 return code, nor check that there is a geni_rspec element in the return struct before referencing it.

 _Imported from trac ticket [#707](http://trac.gpolab.bbn.com/gcf/ticket/707),  created by ahelsing on 09-26-2014 at 14:17, last modified: 10-01-2014 at 12:13_

**Comment by ahelsing** [comment]
Checking for errors now fails. Stupid error.

_Trac comment by ahelsing on 10-01-2014 at 12:04_

**Comment by ahelsing** [comment]
Fixed up finding geni_code under code in return struct.

Also added --ForceUseGetVersionCache to calls to getversion. Use the cache - no reason to keep requerying the AM.

_Trac comment by ahelsing on 10-01-2014 at 12:13_
