### ISSUE TITLE
avoid exception doing string replace on empty string

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#709]
Sarah got this error on cascade:
```
09/29 17:21:05 INFO     stitchhandler.py:1134 Slice urn:publicid:IDN+ch1.gpolab.bbn.com:tutorial+slice+stitch expires on 2014-10-06 21:19:16 UTC
09/29 17:21:05 INFO     stitchhandler.py:675 Calling SCS...
09/29 17:21:05 DEBUG    stitchhandler.py:1552 Sending SCS options {'geni_workflow_paths_merged': True}
09/29 17:21:05 DEBUG    stitchhandler.py:2151 No AMs in AM list to process, so not creating amlist file
Traceback (most recent call last):
  File "/usr/share/geni-ch/portal/gcf/src/stitcher_php.py", line 73, in <module>
    sys.exit(main())
  File "/usr/share/geni-ch/portal/gcf/src/stitcher_php.py", line 60, in main
    raise e
AttributeError: 'NoneType' object has no attribute 'replace'
```

I believe this is does to a string.replace on an empty string

 _Imported from trac ticket [#709](http://trac.gpolab.bbn.com/gcf/ticket/709),  created by ahelsing on 09-30-2014 at 08:30, last modified: 09-30-2014 at 10:08_

**Comment by ahelsing** [comment]
This appears to be caused by a dom.toprettyxml call. It appears to only happen on python2.6

Full stack:
```
  File "/usr/share/geni-ch/portal/gcf-2.7-rc2/src/gcf/omnilib/stitchhandler.py", line 1554, in constructSCSArgs
    return requestDOM.toprettyxml(encoding="utf-8"), options
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 57, in toprettyxml
    self.writexml(writer, "", indent, newl, encoding)
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 1749, in writexml
    node.writexml(writer, indent, addindent, newl)
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 817, in writexml
    node.writexml(writer,indent+addindent,addindent,newl)
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 817, in writexml
    node.writexml(writer,indent+addindent,addindent,newl)
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 812, in writexml
    _write_data(writer, attrs[a_name].value)
  File "/usr/lib/python2.6/xml/dom/minidom.py", line 301, in _write_data
    data = data.replace("&", "&amp;").replace("<", "&lt;")
AttributeError: 'NoneType' object has no attribute 'replace'
```

The error happens in trying to process the value of an attribute on an element. The value appears to be 'None'.

My theory is that this is the `xmlns=""` attribute on the `sliver_type` element that causes this.

Adding code to catch errors turning DOM into xml.


_Trac comment by ahelsing on 09-30-2014 at 10:03_
