### ISSUE TITLE
delete fails with multiple AMs

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#808]
Omni's delete (apiv3) fails when given multiple AMs.

In particular, if AM1 returns an actual struct of slivers, then that overwrites the variable `slivers` that is used when interpreting the results from the 2nd AM, causing bad things to happen.
Symptom:
```
14:09:31 INFO    : Deletion of slivers in slice
urn:publicid:IDN+ch.geni.net:ln-test+slice+ig-nps-ig-pks2v3 at AM nps-ig3
14:09:31 INFO    : [
  {
    "geni_expires": "2015-05-08T20:17:18Z",
    "geni_allocation_status": "geni_unallocated",
    "geni_sliver_urn": "urn:publicid:IDN+instageni.nps.edu+sliver+5696",
    "geni_error": ""
  },
  {
    "geni_expires": "2015-05-08T20:17:18Z",
    "geni_allocation_status": "geni_unallocated",
    "geni_sliver_urn": "urn:publicid:IDN+instageni.nps.edu+sliver+5698",
    "geni_error": ""
  }
]
14:09:34 INFO    :  (PG log url - look here for details on any failures:
https://www.pks2.sdn.uky.edu/spewlogfile.php3?logfile=ed5c7f996462d8b672ad17dc84f804af)
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.9-pre2/src/stitcher.py", line 457, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.9-pre2/src/stitcher.py", line 438, in main
    text, item = call(argv)
  File "/home/lnevers/gcf-2.9-pre2/src/stitcher.py", line 429, in call
    return handler.doStitching(args)
  File "/home/lnevers/gcf-2.9-pre2/src/gcf/omnilib/stitchhandler.py",
line 204, in doStitching
    return self.passToOmni(args)
  File "/home/lnevers/gcf-2.9-pre2/src/gcf/omnilib/stitchhandler.py",
line 790, in passToOmni
    return omni.call(args, self.opts)
  File "/home/lnevers/gcf-2.9-pre2/src/gcf/oscript.py", line 765, in call
    return API_call( framework, config, args, opts, verbose=verbose )
  File "/home/lnevers/gcf-2.9-pre2/src/gcf/oscript.py", line 839, in
API_call
    result = handler._handle(args)
  File "/home/lnevers/gcf-2.9-pre2/src/gcf/omnilib/handler.py", line 90,
in _handle
    (message, val) = getattr(self.amhandler,call)(args[1:])
  File "/home/lnevers/gcf-2.9-pre2/src/gcf/omnilib/amhandler.py", line
4275, in delete
    missingSlivers = self._findMissingSlivers(realres, slivers)
  File "/home/lnevers/gcf-2.9-pre2/src/gcf/omnilib/amhandler.py", line
6385, in _findMissingSlivers
    if not request or request.strip() == "":
AttributeError: 'dict' object has no attribute 'strip'
```

 _Imported from trac ticket [#808](http://trac.gpolab.bbn.com/gcf/ticket/808),  created by ahelsing on 05-08-2015 at 17:16, last modified: 05-08-2015 at 17:33_

**Comment by ahelsing** [comment]
rename the later variable that re-used the name `slivers`

_Trac comment by ahelsing on 05-08-2015 at 17:17_
