### ISSUE TITLE
fix merging comments

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#815]
stacktrace merging manifests when one has a comment and the other does not but has some other child:
```
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:540 combineLinks Considering manifest from <Aggregate ukypks2-ig3>
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:556 Found AM urn:publicid:IDN+pks2.sdn.uky.edu+authority+cm link 'link-1' that has vlantag '1846'
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:748 Created comment to add to template: AM urn:publicid:IDN+pks2.sdn.uky.edu+authority+cm: sliver_id=None vlantag=1846
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:758 Checking if new AM link's CM urn:publicid:IDN+instageni.rutgers.edu+authority+cm is on template
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:758 Checking if new AM link's CM urn:publicid:IDN+al2s.internet2.edu+authority+am is on template
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:758 Checking if new AM link's CM urn:publicid:IDN+pks2.sdn.uky.edu+authority+cm is on template
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:778 Checking if template has property found in AMs link src=interface-2, dst=interface-3
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:787 Comparing to property on template link src=interface-2, dst=interface-3
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:778 Checking if template has property found in AMs link src=interface-3, dst=interface-2
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:787 Comparing to property on template link src=interface-2, dst=interface-3
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:787 Comparing to property on template link src=interface-3, dst=interface-2
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:807 Checking that template has this AMs element found under link: type 1 name link_type value None, attCnt 2, childCnt 0
05/14 11:37:55 DEBUG    ManifestRSpecCombiner.py:815 Comparing with template element under link: AM urn:publicid:IDN+pks2.sdn.uky.edu+authority+cm: sliver_id=None vlantag=1846
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.9-pre3/src/stitcher.py", line 466, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.9-pre3/src/stitcher.py", line 447, in main
    text, item = call(argv)
  File "/home/lnevers/gcf-2.9-pre3/src/stitcher.py", line 438, in call
    return handler.doStitching(args)
  File "/home/lnevers/gcf-2.9-pre3/src/gcf/omnilib/stitchhandler.py",
line 351, in doStitching
    combinedManifest, filename, retVal =
self.getAndSaveCombinedManifest(lastAM)
  File "/home/lnevers/gcf-2.9-pre3/src/gcf/omnilib/stitchhandler.py",
line 985, in getAndSaveCombinedManifest
    combinedManifest = self.combineManifests(self.ams_to_process, lastAM)
  File "/home/lnevers/gcf-2.9-pre3/src/gcf/omnilib/stitchhandler.py",
line 3343, in combineManifests
    combinedManifestDom = combineManifestRSpecs(ams, lastDom)
  File
"/home/lnevers/gcf-2.9-pre3/src/gcf/omnilib/stitch/ManifestRSpecCombiner.py",
line 1200, in combineManifestRSpecs
    return mrc.combine(ams_list, dom_template)
  File
"/home/lnevers/gcf-2.9-pre3/src/gcf/omnilib/stitch/ManifestRSpecCombiner.py",
line 72, in combine
    self.combineLinks(ams_list, dom_template)
  File
"/home/lnevers/gcf-2.9-pre3/src/gcf/omnilib/stitch/ManifestRSpecCombiner.py",
line 816, in combineLinks
    if child.data == child2.data:
AttributeError: Element instance has no attribute 'data'
```

 _Imported from trac ticket [#815](http://trac.gpolab.bbn.com/gcf/ticket/815),  created by ahelsing on 05-14-2015 at 13:17, last modified: 05-14-2015 at 13:20_

**Comment by ahelsing** [comment]
need to check type of comparison child....

_Trac comment by ahelsing on 05-14-2015 at 13:18_
