### ISSUE TITLE
Handle 2 stitcher instances in same Windows directory

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#824]
If 2 stitcher instances run in the same directory on Windows, the 2nd process gets this error:

```
 C:\Users\lnevers\Downloads>stitcher deletesliver lnwin7
 Traceback (most recent call last):
   File "stitcher.py", line 466, in <module>
   File "stitcher.py", line 447, in main
   File "stitcher.py", line 307, in call
 WindowsError: [Error 32] The process cannot access the file because it is being used by another process
```

Apparently on Windows, the `os.rename` of the existing `stitcher.log` to a new copy fails, where on Linux the first copy becomes `stitcher.log.1` but the process continues to write to it successfully.

**Comment by ahelsing** [comment]
Options I see:
 1. This new copy of stitcher writes to something named other than `stitcher.log`
 2. Exit with a suggestion of running in a different directory or using `--fileDir`

**Comment by ahelsing** [comment]
Tom suggests that stitcher should behave as many other programs do: if you download a file in your browser and the suggested filename is taken, it adds a number to the end and renames the new file.

Additionally, this renaming would handle the rename problem (this issue). And it would address Niky's issue #789 to have the stitcher log files named from when the run was.

Logs could be named something like `stitcher-YYYYMMDDHH24MI.log`.

Documentation would have to be updated to help experimenters find the appropriate log file.

**Comment by ahelsing** [comment]
Doing the simple thing for now; a nicer error message. Full solution pushed off to a later release.
