### ISSUE TITLE
Exception combining manifests using fixedEndpoint

### ISSUE THREAD

**Issue by ahelsing** [GENI-NSF/geni-tools#833]
Trying to stitch using a fixed endpoint, got:
```
stitcher.py createsliver fixedE ./stitch-fixedE.rspec -o --fixedEndpoint
14:34:45 INFO    : Configured logging from file
/home/lnevers/gcf-2.9/src/gcf/stitcher_logging.conf
14:34:45 INFO    : Reading slice fixedE credential...
14:34:46 INFO    : Slice
urn:publicid:IDN+ch.geni.net:ln-test+slice+fixedE expires on 2015-06-11
18:33:43 UTC
14:34:46 INFO    : Calling SCS...
14:34:46 INFO    : Multi-AM reservation will include resources from
these aggregates:
14:34:46 INFO    :     <Aggregate al2s>
14:34:46 INFO    :     <Aggregate nps-ig>
14:34:46 INFO    : Adding fake Node endpoint
14:34:46 INFO    : Adding fake interface_ref endpoint on link link
14:34:46 INFO    : Stitcher doing createsliver at <Aggregate nps-ig>...
14:35:05 INFO    : ... Allocation at <Aggregate nps-ig> complete.
14:35:05 INFO    : Stitcher doing createsliver at <Aggregate al2s>...
14:35:10 INFO    : ... Allocation at <Aggregate al2s> complete.
14:35:10 INFO    : All aggregates are complete.
Traceback (most recent call last):
  File "/home/lnevers/gcf-2.9/src/stitcher.py", line 475, in <module>
    sys.exit(main())
  File "/home/lnevers/gcf-2.9/src/stitcher.py", line 456, in main
    text, item = call(argv)
  File "/home/lnevers/gcf-2.9/src/stitcher.py", line 447, in call
    return handler.doStitching(args)
  File "/home/lnevers/gcf-2.9/src/gcf/omnilib/stitchhandler.py", line
357, in doStitching
    combinedManifest, filename, retVal =
self.getAndSaveCombinedManifest(lastAM)
  File "/home/lnevers/gcf-2.9/src/gcf/omnilib/stitchhandler.py", line
1034, in getAndSaveCombinedManifest
    combinedManifest = self.combineManifests(self.ams_to_process, lastAM)
  File "/home/lnevers/gcf-2.9/src/gcf/omnilib/stitchhandler.py", line
3458, in combineManifests
    combinedManifestDom = combineManifestRSpecs(ams, lastDom)
  File
"/home/lnevers/gcf-2.9/src/gcf/omnilib/stitch/ManifestRSpecCombiner.py",
line 1200, in combineManifestRSpecs
    return mrc.combine(ams_list, dom_template)
  File
"/home/lnevers/gcf-2.9/src/gcf/omnilib/stitch/ManifestRSpecCombiner.py",
line 76, in combine
    self.addAggregateDetails(ams_list, dom_template)
  File
"/home/lnevers/gcf-2.9/src/gcf/omnilib/stitch/ManifestRSpecCombiner.py",
line 972, in addAggregateDetails
    am_details = self.computeAMDetails(am)
  File
"/home/lnevers/gcf-2.9/src/gcf/omnilib/stitch/ManifestRSpecCombiner.py",
line 1020, in computeAMDetails
    if hop.import_vlans_from.aggregate == am:
AttributeError: 'NoneType' object has no attribute 'aggregate'
```

**Comment by ahelsing** [comment]
Test request RSpec:
```xml
  <node client_id="ig-nps" component_manager_id="urn:publicid:IDN+instageni.nps.edu+authority+cm" exclusive="false">
    <sliver_type name="emulab-xen"/>
   <services> <execute command="sudo apt-get install iperf -y" shell="sh"/> </services>
    <interface client_id="ig-nps:if0">
      <ip address="192.168.1.2" netmask="255.255.255.0" type="ipv4"/>
    </interface>
  </node>
  <link client_id="link">
    <component_manager name="urn:publicid:IDN+instageni.nps.edu+authority+cm"/>
    <interface_ref client_id="ig-nps:if0"/>
   <component_manager name="urn:publicid:IDN+al2s.internet2.edu+authority+am"/>
  </link>

  <stitching xmlns="http://hpn.east.isi.edu/rspec/ext/stitch/0.1/">
    <path id="link">
      <hop id="1">
   <link id="urn:publicid:IDN+al2s.internet2.edu+interface+sdn-sw.newy32aoa.net.internet2.edu:eth5/2:host-gpolab">
...
             <interfaceMTU>9000</interfaceMTU>
            <vlanRangeAvailability>2646</vlanRangeAvailability>
            <suggestedVLANRange>2646</suggestedVLANRange>
            <vlanTranslation>true</vlanTranslation>
...
   <nextHop>2</nextHop>
   </hop>

   <hop id="2">
   <link id="urn:publicid:IDN+instageni.nps.edu+interface+procurve2:1.19.al2s">
      <remoteLinkId>urn:publicid:IDN+al2s.internet2.edu+interface+sdn-sw.losa.net.internet2.edu:eth5/1:nps-ig</remoteLinkId>
...
          <vlanRangeAvailability>1680-1694</vlanRangeAvailability>
...
```
